version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - local-keycloak
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    depends_on:
      - "postgres"
    container_name: local_keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG

    ports:
      - "8180:8080"
      - "8443:8443"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:
    driver: bridge